# Language Learning Portal - Vocabulary Importer
# Docker Compose Configuration

version: "3"

services:
  # Ollama LLM Service
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
  
  # Vocabulary Importer Application
  vocab-importer:
    image: python:3.9-slim
    container_name: vocab-importer
    ports:
      - "8501:8501"
    working_dir: /app
    command: >
      bash -c "
      pip install --no-cache-dir streamlit pandas requests python-dotenv nest-asyncio aiohttp &&
      streamlit run app.py --server.address=0.0.0.0 --server.port=8501
      "
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - LLM_SERVICE_HOST=ollama-server
      - LLM_SERVICE_PORT=11434
      - LLM_MODEL_ID=${LLM_MODEL_ID:-llama2:13b}
    depends_on:
      - ollama-server
    restart: unless-stopped

# Define volumes for persistent storage
volumes:
  ollama-data:
    # This volume stores the Ollama models
    # This ensures models are preserved across container restarts

# Define default network
networks:
  default:
    driver: bridge 