# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    restart: unless-stopped
    
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - ${LLM_ENDPOINT_PORT:-9000}:11434
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_MODEL_ID: ${LLM_MODEL_ID:-llama3.2:1b}
      host_ip: ${host_ip}
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    
  mega-service:
    image: python:3.10-slim
    container_name: mega-service
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        python app.py
      "
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      LLM_SERVICE_HOST_IP: ollama-server
      LLM_SERVICE_PORT: 11434
      DEFAULT_MODEL: ${LLM_MODEL_ID:-llama3.2:1b}
      DEFAULT_MAX_TOKENS: 1024
      CONNECTION_RETRY_COUNT: 10
      CONNECTION_RETRY_DELAY: 10
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6831
      SERVICE_NAME: llm-mega-service
    depends_on:
      ollama-server:
        condition: service_healthy
      jaeger:
        condition: service_started
    restart: unless-stopped

networks:
  default:
    driver: bridge
    
volumes:
  ollama-data: